### ISSUE TITLE
Build instructions don't mention building bba

### ISSUE THREAD

**Issue by vmedea** [open-tool-forge/fpga-toolchain#56]
The build instructions in the README don't mention building the bba file. I guess it was recently split up? I noticed that the script `build_bba.sh` needs to be run first, to generate the file `ecp5-bba-linux_x86_64-nightly.tar.gz`, otherwise `build.sh` fails on a tar command in the `compile_nextpnr_ecp5` step.
(there also appears to need to be a `clean.sh` step in between `build_bba.sh` and `build.sh` otherwise it gets confused about the pre-existing git checkout, but if you're not careful to first copy the generated file out, you'll end up losing it :innocent: )

**Comment by edbordin** [comment]
Yes, fair point, I got nextpnr working early on and since then haven't been running full builds locally. So as you point out, it's very clunky to run the whole lot locally.

I will try to get around to making the bba thing smoother locally and write some up-to-date dev instructions (the ones in the readme are mostly just inherited from fomu-toolchain) so that I don't scare away any other potential contributors :P
